<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('countries')->delete();
        $countries = [
            ['id' => 1,'code' => 'AF' ,'name' => "Afghanistan",'phonecode' => 93],
            ['id' => 2,'code' => 'AL' ,'name' => "Albania",'phonecode' => 355],
            ['id' => 3,'code' => 'DZ' ,'name' => "Algeria",'phonecode' => 213],
            ['id' => 4,'code' => 'AS' ,'name' => "American Samoa",'phonecode' => 1684],
            ['id' => 5,'code' => 'AD' ,'name' => "Andorra",'phonecode' => 376],
            ['id' => 6,'code' => 'AO' ,'name' => "Angola",'phonecode' => 244],
            ['id' => 7,'code' => 'AI' ,'name' => "Anguilla",'phonecode' => 1264],
            ['id' => 8,'code' => 'AQ' ,'name' => "Antarctica",'phonecode' => 0],
            ['id' => 9,'code' => 'AG' ,'name' => "Antigua And Barbuda",'phonecode' => 1268],
            ['id' => 10,'code' => 'AR','name' => "Argentina",'phonecode' => 54],
            ['id' => 11,'code' => 'AM','name' => "Armenia",'phonecode' => 374],
            ['id' => 12,'code' => 'AW','name' => "Aruba",'phonecode' => 297],
            ['id' => 13,'code' => 'AU','name' => "Australia",'phonecode' => 61],
            ['id' => 14,'code' => 'AT','name' => "Austria",'phonecode' => 43],
            ['id' => 15,'code' => 'AZ','name' => "Azerbaijan",'phonecode' => 994],
            ['id' => 16,'code' => 'BS','name' => "Bahamas The",'phonecode' => 1242],
            ['id' => 17,'code' => 'BH','name' => "Bahrain",'phonecode' => 973],
            ['id' => 18,'code' => 'BD','name' => "Bangladesh",'phonecode' => 880],
            ['id' => 19,'code' => 'BB','name' => "Barbados",'phonecode' => 1246],
            ['id' => 20,'code' => 'BY','name' => "Belarus",'phonecode' => 375],
            ['id' => 21,'code' => 'BE','name' => "Belgium",'phonecode' => 32],
            ['id' => 22,'code' => 'BZ','name' => "Belize",'phonecode' => 501],
            ['id' => 23,'code' => 'BJ','name' => "Benin",'phonecode' => 229],
            ['id' => 24,'code' => 'BM','name' => "Bermuda",'phonecode' => 1441],
            ['id' => 25,'code' => 'BT','name' => "Bhutan",'phonecode' => 975],
            ['id' => 26,'code' => 'BO','name' => "Bolivia",'phonecode' => 591],
            ['id' => 27,'code' => 'BA','name' => "Bosnia and Herzegovina",'phonecode' => 387],
            ['id' => 28,'code' => 'BW','name' => "Botswana",'phonecode' => 267],
            ['id' => 29,'code' => 'BV','name' => "Bouvet Island",'phonecode' => 0],
            ['id' => 30,'code' => 'BR','name' => "Brazil",'phonecode' => 55],
            ['id' => 31,'code' => 'IO','name' => "British Indian Ocean Territory",'phonecode' => 246],
            ['id' => 32,'code' => 'BN','name' => "Brunei",'phonecode' => 673],
            ['id' => 33,'code' => 'BG','name' => "Bulgaria",'phonecode' => 359],
            ['id' => 34,'code' => 'BF','name' => "Burkina Faso",'phonecode' => 226],
            ['id' => 35,'code' => 'BI','name' => "Burundi",'phonecode' => 257],
            ['id' => 36,'code' => 'KH','name' => "Cambodia",'phonecode' => 855],
            ['id' => 37,'code' => 'CM','name' => "Cameroon",'phonecode' => 237],
            ['id' => 38,'code' => 'CA','name' => "Canada",'phonecode' => 1],
            ['id' => 39,'code' => 'CV','name' => "Cape Verde",'phonecode' => 238],
            ['id' => 40,'code' => 'KY','name' => "Cayman Islands",'phonecode' => 1345],
            ['id' => 41,'code' => 'CF','name' => "Central African Republic",'phonecode' => 236],
            ['id' => 42,'code' => 'TD','name' => "Chad",'phonecode' => 235],
            ['id' => 43,'code' => 'CL','name' => "Chile",'phonecode' => 56],
            ['id' => 44,'code' => 'CN','name' => "China",'phonecode' => 86],
            ['id' => 45,'code' => 'CX','name' => "Christmas Island",'phonecode' => 61],
            ['id' => 46,'code' => 'CC','name' => "Cocos (Keeling) Islands",'phonecode' => 672],
            ['id' => 47,'code' => 'CO','name' => "Colombia",'phonecode' => 57],
            ['id' => 48,'code' => 'KM','name' => "Comoros",'phonecode' => 269],
            ['id' => 49,'code' => 'CG','name' => "Congo",'phonecode' => 242],
            ['id' => 50,'code' => 'CD','name' => "Congo The Democratic Republic Of The",'phonecode' => 242],
            ['id' => 51,'code' => 'CK','name' => "Cook Islands",'phonecode' => 682],
            ['id' => 52,'code' => 'CR','name' => "Costa Rica",'phonecode' => 506],
            ['id' => 53,'code' => 'CI','name' => "Cote D Ivoire (Ivory Coast)",'phonecode' => 225],
            ['id' => 54,'code' => 'HR','name' => "Croatia (Hrvatska)",'phonecode' => 385],
            ['id' => 55,'code' => 'CU','name' => "Cuba",'phonecode' => 53],
            ['id' => 56,'code' => 'CY','name' => "Cyprus",'phonecode' => 357],
            ['id' => 57,'code' => 'CZ','name' => "Czech Republic",'phonecode' => 420],
            ['id' => 58,'code' => 'DK','name' => "Denmark",'phonecode' => 45],
            ['id' => 59,'code' => 'DJ','name' => "Djibouti",'phonecode' => 253],
            ['id' => 60,'code' => 'DM','name' => "Dominica",'phonecode' => 1767],
            ['id' => 61,'code' => 'DO','name' => "Dominican Republic",'phonecode' => 1809],
            ['id' => 62,'code' => 'TP','name' => "East Timor",'phonecode' => 670],
            ['id' => 63,'code' => 'EC','name' => "Ecuador",'phonecode' => 593],
            ['id' => 64,'code' => 'EG','name' => "Egypt",'phonecode' => 20],
            ['id' => 65,'code' => 'SV','name' => "El Salvador",'phonecode' => 503],
            ['id' => 66,'code' => 'GQ','name' => "Equatorial Guinea",'phonecode' => 240],
            ['id' => 67,'code' => 'ER','name' => "Eritrea",'phonecode' => 291],
            ['id' => 68,'code' => 'EE','name' => "Estonia",'phonecode' => 372],
            ['id' => 69,'code' => 'ET','name' => "Ethiopia",'phonecode' => 251],
            ['id' => 70,'code' => 'XA','name' => "External Territories of Australia",'phonecode' => 61],
            ['id' => 71,'code' => 'FK','name' => "Falkland Islands",'phonecode' => 500],
            ['id' => 72,'code' => 'FO','name' => "Faroe Islands",'phonecode' => 298],
            ['id' => 73,'code' => 'FJ','name' => "Fiji Islands",'phonecode' => 679],
            ['id' => 74,'code' => 'FI','name' => "Finland",'phonecode' => 358],
            ['id' => 75,'code' => 'FR','name' => "France",'phonecode' => 33],
            ['id' => 76,'code' => 'GF','name' => "French Guiana",'phonecode' => 594],
            ['id' => 77,'code' => 'PF','name' => "French Polynesia",'phonecode' => 689],
            ['id' => 78,'code' => 'TF','name' => "French Southern Territories",'phonecode' => 0],
            ['id' => 79,'code' => 'GA','name' => "Gabon",'phonecode' => 241],
            ['id' => 80,'code' => 'GM','name' => "Gambia The",'phonecode' => 220],
            ['id' => 81,'code' => 'GE','name' => "Georgia",'phonecode' => 995],
            ['id' => 82,'code' => 'DE','name' => "Germany",'phonecode' => 49],
            ['id' => 83,'code' => 'GH','name' => "Ghana",'phonecode' => 233],
            ['id' => 84,'code' => 'GI','name' => "Gibraltar",'phonecode' => 350],
            ['id' => 85,'code' => 'GR','name' => "Greece",'phonecode' => 30],
            ['id' => 86,'code' => 'GL','name' => "Greenland",'phonecode' => 299],
            ['id' => 87,'code' => 'GD','name' => "Grenada",'phonecode' => 1473],
            ['id' => 88,'code' => 'GP','name' => "Guadeloupe",'phonecode' => 590],
            ['id' => 89,'code' => 'GU','name' => "Guam",'phonecode' => 1671],
            ['id' => 90,'code' => 'GT','name' => "Guatemala",'phonecode' => 502],
            ['id' => 91,'code' => 'XU','name' => "Guernsey and Alderney",'phonecode' => 44],
            ['id' => 92,'code' => 'GN','name' => "Guinea",'phonecode' => 224],
            ['id' => 93,'code' => 'GW','name' => "Guinea-Bissau",'phonecode' => 245],
            ['id' => 94,'code' => 'GY','name' => "Guyana",'phonecode' => 592],
            ['id' => 95,'code' => 'HT','name' => "Haiti",'phonecode' => 509],
            ['id' => 96,'code' => 'HM','name' => "Heard and McDonald Islands",'phonecode' => 0],
            ['id' => 97,'code' => 'HN','name' => "Honduras",'phonecode' => 504],
            ['id' => 98,'code' => 'HK','name' => "Hong Kong S.A.R.",'phonecode' => 852],
            ['id' => 99,'code' => 'HU','name' => "Hungary",'phonecode' => 36],
            ['id' => 100,'code' => 'IS','name' => "Iceland",'phonecode' => 354],
            ['id' => 101,'code' => 'IN','name' => "India",'phonecode' => 91],
            ['id' => 102,'code' => 'ID','name' => "Indonesia",'phonecode' => 62],
            ['id' => 103,'code' => 'IR','name' => "Iran",'phonecode' => 98],
            ['id' => 104,'code' => 'IQ','name' => "Iraq",'phonecode' => 964],
            ['id' => 105,'code' => 'IE','name' => "Ireland",'phonecode' => 353],
            ['id' => 106,'code' => 'IL','name' => "Israel",'phonecode' => 972],
            ['id' => 107,'code' => 'IT','name' => "Italy",'phonecode' => 39],
            ['id' => 108,'code' => 'JM','name' => "Jamaica",'phonecode' => 1876],
            ['id' => 109,'code' => 'JP','name' => "Japan",'phonecode' => 81],
            ['id' => 110,'code' => 'XJ','name' => "Jersey",'phonecode' => 44],
            ['id' => 111,'code' => 'JO','name' => "Jordan",'phonecode' => 962],
            ['id' => 112,'code' => 'KZ','name' => "Kazakhstan",'phonecode' => 7],
            ['id' => 113,'code' => 'KE','name' => "Kenya",'phonecode' => 254],
            ['id' => 114,'code' => 'KI','name' => "Kiribati",'phonecode' => 686],
            ['id' => 115,'code' => 'KP','name' => "Korea North",'phonecode' => 850],
            ['id' => 116,'code' => 'KR','name' => "Korea South",'phonecode' => 82],
            ['id' => 117,'code' => 'KW','name' => "Kuwait",'phonecode' => 965],
            ['id' => 118,'code' => 'KG','name' => "Kyrgyzstan",'phonecode' => 996],
            ['id' => 119,'code' => 'LA','name' => "Laos",'phonecode' => 856],
            ['id' => 120,'code' => 'LV','name' => "Latvia",'phonecode' => 371],
            ['id' => 121,'code' => 'LB','name' => "Lebanon",'phonecode' => 961],
            ['id' => 122,'code' => 'LS','name' => "Lesotho",'phonecode' => 266],
            ['id' => 123,'code' => 'LR','name' => "Liberia",'phonecode' => 231],
            ['id' => 124,'code' => 'LY','name' => "Libya",'phonecode' => 218],
            ['id' => 125,'code' => 'LI','name' => "Liechtenstein",'phonecode' => 423],
            ['id' => 126,'code' => 'LT','name' => "Lithuania",'phonecode' => 370],
            ['id' => 127,'code' => 'LU','name' => "Luxembourg",'phonecode' => 352],
            ['id' => 128,'code' => 'MO','name' => "Macau S.A.R.",'phonecode' => 853],
            ['id' => 129,'code' => 'MK','name' => "Macedonia",'phonecode' => 389],
            ['id' => 130,'code' => 'MG','name' => "Madagascar",'phonecode' => 261],
            ['id' => 131,'code' => 'MW','name' => "Malawi",'phonecode' => 265],
            ['id' => 132,'code' => 'MY','name' => "Malaysia",'phonecode' => 60],
            ['id' => 133,'code' => 'MV','name' => "Maldives",'phonecode' => 960],
            ['id' => 134,'code' => 'ML','name' => "Mali",'phonecode' => 223],
            ['id' => 135,'code' => 'MT','name' => "Malta",'phonecode' => 356],
            ['id' => 136,'code' => 'XM','name' => "Man (Isle of)",'phonecode' => 44],
            ['id' => 137,'code' => 'MH','name' => "Marshall Islands",'phonecode' => 692],
            ['id' => 138,'code' => 'MQ','name' => "Martinique",'phonecode' => 596],
            ['id' => 139,'code' => 'MR','name' => "Mauritania",'phonecode' => 222],
            ['id' => 140,'code' => 'MU','name' => "Mauritius",'phonecode' => 230],
            ['id' => 141,'code' => 'YT','name' => "Mayotte",'phonecode' => 269],
            ['id' => 142,'code' => 'MX','name' => "Mexico",'phonecode' => 52],
            ['id' => 143,'code' => 'FM','name' => "Micronesia",'phonecode' => 691],
            ['id' => 144,'code' => 'MD','name' => "Moldova",'phonecode' => 373],
            ['id' => 145,'code' => 'MC','name' => "Monaco",'phonecode' => 377],
            ['id' => 146,'code' => 'MN','name' => "Mongolia",'phonecode' => 976],
            ['id' => 147,'code' => 'MS','name' => "Montserrat",'phonecode' => 1664],
            ['id' => 148,'code' => 'MA','name' => "Morocco",'phonecode' => 212],
            ['id' => 149,'code' => 'MZ','name' => "Mozambique",'phonecode' => 258],
            ['id' => 150,'code' => 'MM','name' => "Myanmar",'phonecode' => 95],
            ['id' => 151,'code' => 'NA','name' => "Namibia",'phonecode' => 264],
            ['id' => 152,'code' => 'NR','name' => "Nauru",'phonecode' => 674],
            ['id' => 153,'code' => 'NP','name' => "Nepal",'phonecode' => 977],
            ['id' => 154,'code' => 'AN','name' => "Netherlands Antilles",'phonecode' => 599],
            ['id' => 155,'code' => 'NL','name' => "Netherlands The",'phonecode' => 31],
            ['id' => 156,'code' => 'NC','name' => "New Caledonia",'phonecode' => 687],
            ['id' => 157,'code' => 'NZ','name' => "New Zealand",'phonecode' => 64],
            ['id' => 158,'code' => 'NI','name' => "Nicaragua",'phonecode' => 505],
            ['id' => 159,'code' => 'NE','name' => "Niger",'phonecode' => 227],
            ['id' => 160,'code' => 'NG','name' => "Nigeria",'phonecode' => 234],
            ['id' => 161,'code' => 'NU','name' => "Niue",'phonecode' => 683],
            ['id' => 162,'code' => 'NF','name' => "Norfolk Island",'phonecode' => 672],
            ['id' => 163,'code' => 'MP','name' => "Northern Mariana Islands",'phonecode' => 1670],
            ['id' => 164,'code' => 'NO','name' => "Norway",'phonecode' => 47],
            ['id' => 165,'code' => 'OM','name' => "Oman",'phonecode' => 968],
            ['id' => 166,'code' => 'PK','name' => "Pakistan",'phonecode' => 92],
            ['id' => 167,'code' => 'PW','name' => "Palau",'phonecode' => 680],
            ['id' => 168,'code' => 'PS','name' => "Palestinian Territory Occupied",'phonecode' => 970],
            ['id' => 169,'code' => 'PA','name' => "Panama",'phonecode' => 507],
            ['id' => 170,'code' => 'PG','name' => "Papua new Guinea",'phonecode' => 675],
            ['id' => 171,'code' => 'PY','name' => "Paraguay",'phonecode' => 595],
            ['id' => 172,'code' => 'PE','name' => "Peru",'phonecode' => 51],
            ['id' => 173,'code' => 'PH','name' => "Philippines",'phonecode' => 63],
            ['id' => 174,'code' => 'PN','name' => "Pitcairn Island",'phonecode' => 0],
            ['id' => 175,'code' => 'PL','name' => "Poland",'phonecode' => 48],
            ['id' => 176,'code' => 'PT','name' => "Portugal",'phonecode' => 351],
            ['id' => 177,'code' => 'PR','name' => "Puerto Rico",'phonecode' => 1787],
            ['id' => 178,'code' => 'QA','name' => "Qatar",'phonecode' => 974],
            ['id' => 179,'code' => 'RE','name' => "Reunion",'phonecode' => 262],
            ['id' => 180,'code' => 'RO','name' => "Romania",'phonecode' => 40],
            ['id' => 181,'code' => 'RU','name' => "Russia",'phonecode' => 70],
            ['id' => 182,'code' => 'RW','name' => "Rwanda",'phonecode' => 250],
            ['id' => 183,'code' => 'SH','name' => "Saint Helena",'phonecode' => 290],
            ['id' => 184,'code' => 'KN','name' => "Saint Kitts And Nevis",'phonecode' => 1869],
            ['id' => 185,'code' => 'LC','name' => "Saint Lucia",'phonecode' => 1758],
            ['id' => 186,'code' => 'PM','name' => "Saint Pierre and Miquelon",'phonecode' => 508],
            ['id' => 187,'code' => 'VC','name' => "Saint Vincent And The Grenadines",'phonecode' => 1784],
            ['id' => 188,'code' => 'WS','name' => "Samoa",'phonecode' => 684],
            ['id' => 189,'code' => 'SM','name' => "San Marino",'phonecode' => 378],
            ['id' => 190,'code' => 'ST','name' => "Sao Tome and Principe",'phonecode' => 239],
            ['id' => 191,'code' => 'SA','name' => "Saudi Arabia",'phonecode' => 966],
            ['id' => 192,'code' => 'SN','name' => "Senegal",'phonecode' => 221],
            ['id' => 193,'code' => 'RS','name' => "Serbia",'phonecode' => 381],
            ['id' => 194,'code' => 'SC','name' => "Seychelles",'phonecode' => 248],
            ['id' => 195,'code' => 'SL','name' => "Sierra Leone",'phonecode' => 232],
            ['id' => 196,'code' => 'SG','name' => "Singapore",'phonecode' => 65],
            ['id' => 197,'code' => 'SK','name' => "Slovakia",'phonecode' => 421],
            ['id' => 198,'code' => 'SI','name' => "Slovenia",'phonecode' => 386],
            ['id' => 199,'code' => 'XG','name' => "Smaller Territories of the UK",'phonecode' => 44],
            ['id' => 200,'code' => 'SB','name' => "Solomon Islands",'phonecode' => 677],
            ['id' => 201,'code' => 'SO','name' => "Somalia",'phonecode' => 252],
            ['id' => 202,'code' => 'ZA','name' => "South Africa",'phonecode' => 27],
            ['id' => 203,'code' => 'GS','name' => "South Georgia",'phonecode' => 0],
            ['id' => 204,'code' => 'SS','name' => "South Sudan",'phonecode' => 211],
            ['id' => 205,'code' => 'ES','name' => "Spain",'phonecode' => 34],
            ['id' => 206,'code' => 'LK','name' => "Sri Lanka",'phonecode' => 94],
            ['id' => 207,'code' => 'SD','name' => "Sudan",'phonecode' => 249],
            ['id' => 208,'code' => 'SR','name' => "Suriname",'phonecode' => 597],
            ['id' => 209,'code' => 'SJ','name' => "Svalbard And Jan Mayen Islands",'phonecode' => 47],
            ['id' => 210,'code' => 'SZ','name' => "Swaziland",'phonecode' => 268],
            ['id' => 211,'code' => 'SE','name' => "Sweden",'phonecode' => 46],
            ['id' => 212,'code' => 'CH','name' => "Switzerland",'phonecode' => 41],
            ['id' => 213,'code' => 'SY','name' => "Syria",'phonecode' => 963],
            ['id' => 214,'code' => 'TW','name' => "Taiwan",'phonecode' => 886],
            ['id' => 215,'code' => 'TJ','name' => "Tajikistan",'phonecode' => 992],
            ['id' => 216,'code' => 'TZ','name' => "Tanzania",'phonecode' => 255],
            ['id' => 217,'code' => 'TH','name' => "Thailand",'phonecode' => 66],
            ['id' => 218,'code' => 'TG','name' => "Togo",'phonecode' => 228],
            ['id' => 219,'code' => 'TK','name' => "Tokelau",'phonecode' => 690],
            ['id' => 220,'code' => 'TO','name' => "Tonga",'phonecode' => 676],
            ['id' => 221,'code' => 'TT','name' => "Trinidad And Tobago",'phonecode' => 1868],
            ['id' => 222,'code' => 'TN','name' => "Tunisia",'phonecode' => 216],
            ['id' => 223,'code' => 'TR','name' => "Turkey",'phonecode' => 90],
            ['id' => 224,'code' => 'TM','name' => "Turkmenistan",'phonecode' => 7370],
            ['id' => 225,'code' => 'TC','name' => "Turks And Caicos Islands",'phonecode' => 1649],
            ['id' => 226,'code' => 'TV','name' => "Tuvalu",'phonecode' => 688],
            ['id' => 227,'code' => 'UG','name' => "Uganda",'phonecode' => 256],
            ['id' => 228,'code' => 'UA','name' => "Ukraine",'phonecode' => 380],
            ['id' => 229,'code' => 'AE','name' => "United Arab Emirates",'phonecode' => 971],
            ['id' => 230,'code' => 'GB','name' => "United Kingdom",'phonecode' => 44],
            ['id' => 231,'code' => 'US','name' => "United States",'phonecode' => 1],
            ['id' => 232,'code' => 'UM','name' => "United States Minor Outlying Islands",'phonecode' => 1],
            ['id' => 233,'code' => 'UY','name' => "Uruguay",'phonecode' => 598],
            ['id' => 234,'code' => 'UZ','name' => "Uzbekistan",'phonecode' => 998],
            ['id' => 235,'code' => 'VU','name' => "Vanuatu",'phonecode' => 678],
            ['id' => 236,'code' => 'VA','name' => "Vatican City State (Holy See)",'phonecode' => 39],
            ['id' => 237,'code' => 'VE','name' => "Venezuela",'phonecode' => 58],
            ['id' => 238,'code' => 'VN','name' => "Vietnam",'phonecode' => 84],
            ['id' => 239,'code' => 'VG','name' => "Virgin Islands (British)",'phonecode' => 1284],
            ['id' => 240,'code' => 'VI','name' => "Virgin Islands (US)",'phonecode' => 1340],
            ['id' => 241,'code' => 'WF','name' => "Wallis And Futuna Islands",'phonecode' => 681],
            ['id' => 242,'code' => 'EH','name' => "Western Sahara",'phonecode' => 212],
            ['id' => 243,'code' => 'YE','name' => "Yemen",'phonecode' => 967],
            ['id' => 244,'code' => 'YU','name' => "Yugoslavia",'phonecode' => 38],
            ['id' => 245,'code' => 'ZM','name' => "Zambia",'phonecode' => 260],
            ['id' => 246,'code' => 'ZW','name' => "Zimbabwe",'phonecode' => 263],
        ];
        DB::table('countries')->insert($countries);
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        /*$items = [

            ['id' => 1, 'shortcode' => 'AF', 'title' => 'Afghanistan'],
            ['id' => 2, 'shortcode' => 'AL', 'title' => 'Albania'],
            ['id' => 3, 'shortcode' => 'DZ', 'title' => 'Algeria'],
            ['id' => 4, 'shortcode' => 'AS', 'title' => 'American Samoa'],
            ['id' => 5, 'shortcode' => 'AD', 'title' => 'Andorra'],
            ['id' => 6, 'shortcode' => 'AO', 'title' => 'Angola'],
            ['id' => 7, 'shortcode' => 'AI', 'title' => 'Anguilla'],
            ['id' => 8, 'shortcode' => 'AQ', 'title' => 'Antarctica'],
            ['id' => 9, 'shortcode' => 'AG', 'title' => 'Antigua and Barbuda'],
            ['id' => 10, 'shortcode' => 'AR', 'title' => 'Argentina'],
            ['id' => 11, 'shortcode' => 'AM', 'title' => 'Armenia'],
            ['id' => 12, 'shortcode' => 'AW', 'title' => 'Aruba'],
            ['id' => 13, 'shortcode' => 'AU', 'title' => 'Australia'],
            ['id' => 14, 'shortcode' => 'AT', 'title' => 'Austria'],
            ['id' => 15, 'shortcode' => 'AZ', 'title' => 'Azerbaijan'],
            ['id' => 16, 'shortcode' => 'BS', 'title' => 'Bahamas'],
            ['id' => 17, 'shortcode' => 'BH', 'title' => 'Bahrain'],
            ['id' => 18, 'shortcode' => 'BD', 'title' => 'Bangladesh'],
            ['id' => 19, 'shortcode' => 'BB', 'title' => 'Barbados'],
            ['id' => 20, 'shortcode' => 'BY', 'title' => 'Belarus'],
            ['id' => 21, 'shortcode' => 'BE', 'title' => 'Belgium'],
            ['id' => 22, 'shortcode' => 'BZ', 'title' => 'Belize'],
            ['id' => 23, 'shortcode' => 'BJ', 'title' => 'Benin'],
            ['id' => 24, 'shortcode' => 'BM', 'title' => 'Bermuda'],
            ['id' => 25, 'shortcode' => 'BT', 'title' => 'Bhutan'],
            ['id' => 26, 'shortcode' => 'BO', 'title' => 'Bolivia'],
            ['id' => 27, 'shortcode' => 'BA', 'title' => 'Bosnia and Herzegovina'],
            ['id' => 28, 'shortcode' => 'BW', 'title' => 'Botswana'],
            ['id' => 29, 'shortcode' => 'BV', 'title' => 'Bouvet Island'],
            ['id' => 30, 'shortcode' => 'BR', 'title' => 'Brazil'],
            ['id' => 31, 'shortcode' => 'BQ', 'title' => 'British Antarctic Territory'],
            ['id' => 32, 'shortcode' => 'IO', 'title' => 'British Indian Ocean Territory'],
            ['id' => 33, 'shortcode' => 'VG', 'title' => 'British Virgin Islands'],
            ['id' => 34, 'shortcode' => 'BN', 'title' => 'Brunei'],
            ['id' => 35, 'shortcode' => 'BG', 'title' => 'Bulgaria'],
            ['id' => 36, 'shortcode' => 'BF', 'title' => 'Burkina Faso'],
            ['id' => 37, 'shortcode' => 'BI', 'title' => 'Burundi'],
            ['id' => 38, 'shortcode' => 'KH', 'title' => 'Cambodia'],
            ['id' => 39, 'shortcode' => 'CM', 'title' => 'Cameroon'],
            ['id' => 40, 'shortcode' => 'CA', 'title' => 'Canada'],
            ['id' => 41, 'shortcode' => 'CT', 'title' => 'Canton and Enderbury Islands'],
            ['id' => 42, 'shortcode' => 'CV', 'title' => 'Cape Verde'],
            ['id' => 43, 'shortcode' => 'KY', 'title' => 'Cayman Islands'],
            ['id' => 44, 'shortcode' => 'CF', 'title' => 'Central African Republic'],
            ['id' => 45, 'shortcode' => 'TD', 'title' => 'Chad'],
            ['id' => 46, 'shortcode' => 'CL', 'title' => 'Chile'],
            ['id' => 47, 'shortcode' => 'CN', 'title' => 'China'],
            ['id' => 48, 'shortcode' => 'CX', 'title' => 'Christmas Island'],
            ['id' => 49, 'shortcode' => 'CC', 'title' => 'Cocos [Keeling] Islands'],
            ['id' => 50, 'shortcode' => 'CO', 'title' => 'Colombia'],
            ['id' => 51, 'shortcode' => 'KM', 'title' => 'Comoros'],
            ['id' => 52, 'shortcode' => 'CG', 'title' => 'Congo - Brazzaville'],
            ['id' => 53, 'shortcode' => 'CD', 'title' => 'Congo - Kinshasa'],
            ['id' => 54, 'shortcode' => 'CK', 'title' => 'Cook Islands'],
            ['id' => 55, 'shortcode' => 'CR', 'title' => 'Costa Rica'],
            ['id' => 56, 'shortcode' => 'HR', 'title' => 'Croatia'],
            ['id' => 57, 'shortcode' => 'CU', 'title' => 'Cuba'],
            ['id' => 58, 'shortcode' => 'CY', 'title' => 'Cyprus'],
            ['id' => 59, 'shortcode' => 'CZ', 'title' => 'Czech Republic'],
            ['id' => 60, 'shortcode' => 'CI', 'title' => 'Côte d’Ivoire'],
            ['id' => 61, 'shortcode' => 'DK', 'title' => 'Denmark'],
            ['id' => 62, 'shortcode' => 'DJ', 'title' => 'Djibouti'],
            ['id' => 63, 'shortcode' => 'DM', 'title' => 'Dominica'],
            ['id' => 64, 'shortcode' => 'DO', 'title' => 'Dominican Republic'],
            ['id' => 65, 'shortcode' => 'NQ', 'title' => 'Dronning Maud Land'],
            ['id' => 66, 'shortcode' => 'DD', 'title' => 'East Germany'],
            ['id' => 67, 'shortcode' => 'EC', 'title' => 'Ecuador'],
            ['id' => 68, 'shortcode' => 'EG', 'title' => 'Egypt'],
            ['id' => 69, 'shortcode' => 'SV', 'title' => 'El Salvador'],
            ['id' => 70, 'shortcode' => 'GQ', 'title' => 'Equatorial Guinea'],
            ['id' => 71, 'shortcode' => 'ER', 'title' => 'Eritrea'],
            ['id' => 72, 'shortcode' => 'EE', 'title' => 'Estonia'],
            ['id' => 73, 'shortcode' => 'ET', 'title' => 'Ethiopia'],
            ['id' => 74, 'shortcode' => 'FK', 'title' => 'Falkland Islands'],
            ['id' => 75, 'shortcode' => 'FO', 'title' => 'Faroe Islands'],
            ['id' => 76, 'shortcode' => 'FJ', 'title' => 'Fiji'],
            ['id' => 77, 'shortcode' => 'FI', 'title' => 'Finland'],
            ['id' => 78, 'shortcode' => 'FR', 'title' => 'France'],
            ['id' => 79, 'shortcode' => 'GF', 'title' => 'French Guiana'],
            ['id' => 80, 'shortcode' => 'PF', 'title' => 'French Polynesia'],
            ['id' => 81, 'shortcode' => 'TF', 'title' => 'French Southern Territories'],
            ['id' => 82, 'shortcode' => 'FQ', 'title' => 'French Southern and Antarctic Territories'],
            ['id' => 83, 'shortcode' => 'GA', 'title' => 'Gabon'],
            ['id' => 84, 'shortcode' => 'GM', 'title' => 'Gambia'],
            ['id' => 85, 'shortcode' => 'GE', 'title' => 'Georgia'],
            ['id' => 86, 'shortcode' => 'DE', 'title' => 'Germany'],
            ['id' => 87, 'shortcode' => 'GH', 'title' => 'Ghana'],
            ['id' => 88, 'shortcode' => 'GI', 'title' => 'Gibraltar'],
            ['id' => 89, 'shortcode' => 'GR', 'title' => 'Greece'],
            ['id' => 90, 'shortcode' => 'GL', 'title' => 'Greenland'],
            ['id' => 91, 'shortcode' => 'GD', 'title' => 'Grenada'],
            ['id' => 92, 'shortcode' => 'GP', 'title' => 'Guadeloupe'],
            ['id' => 93, 'shortcode' => 'GU', 'title' => 'Guam'],
            ['id' => 94, 'shortcode' => 'GT', 'title' => 'Guatemala'],
            ['id' => 95, 'shortcode' => 'GG', 'title' => 'Guernsey'],
            ['id' => 96, 'shortcode' => 'GN', 'title' => 'Guinea'],
            ['id' => 97, 'shortcode' => 'GW', 'title' => 'Guinea-Bissau'],
            ['id' => 98, 'shortcode' => 'GY', 'title' => 'Guyana'],
            ['id' => 99, 'shortcode' => 'HT', 'title' => 'Haiti'],
            ['id' => 100, 'shortcode' => 'HM', 'title' => 'Heard Island and McDonald Islands'],
            ['id' => 101, 'shortcode' => 'HN', 'title' => 'Honduras'],
            ['id' => 102, 'shortcode' => 'HK', 'title' => 'Hong Kong SAR China'],
            ['id' => 103, 'shortcode' => 'HU', 'title' => 'Hungary'],
            ['id' => 104, 'shortcode' => 'IS', 'title' => 'Iceland'],
            ['id' => 105, 'shortcode' => 'IN', 'title' => 'India'],
            ['id' => 106, 'shortcode' => 'ID', 'title' => 'Indonesia'],
            ['id' => 107, 'shortcode' => 'IR', 'title' => 'Iran'],
            ['id' => 108, 'shortcode' => 'IQ', 'title' => 'Iraq'],
            ['id' => 109, 'shortcode' => 'IE', 'title' => 'Ireland'],
            ['id' => 110, 'shortcode' => 'IM', 'title' => 'Isle of Man'],
            ['id' => 111, 'shortcode' => 'IL', 'title' => 'Israel'],
            ['id' => 112, 'shortcode' => 'IT', 'title' => 'Italy'],
            ['id' => 113, 'shortcode' => 'JM', 'title' => 'Jamaica'],
            ['id' => 114, 'shortcode' => 'JP', 'title' => 'Japan'],
            ['id' => 115, 'shortcode' => 'JE', 'title' => 'Jersey'],
            ['id' => 116, 'shortcode' => 'JT', 'title' => 'Johnston Island'],
            ['id' => 117, 'shortcode' => 'JO', 'title' => 'Jordan'],
            ['id' => 118, 'shortcode' => 'KZ', 'title' => 'Kazakhstan'],
            ['id' => 119, 'shortcode' => 'KE', 'title' => 'Kenya'],
            ['id' => 120, 'shortcode' => 'KI', 'title' => 'Kiribati'],
            ['id' => 121, 'shortcode' => 'KW', 'title' => 'Kuwait'],
            ['id' => 122, 'shortcode' => 'KG', 'title' => 'Kyrgyzstan'],
            ['id' => 123, 'shortcode' => 'LA', 'title' => 'Laos'],
            ['id' => 124, 'shortcode' => 'LV', 'title' => 'Latvia'],
            ['id' => 125, 'shortcode' => 'LB', 'title' => 'Lebanon'],
            ['id' => 126, 'shortcode' => 'LS', 'title' => 'Lesotho'],
            ['id' => 127, 'shortcode' => 'LR', 'title' => 'Liberia'],
            ['id' => 128, 'shortcode' => 'LY', 'title' => 'Libya'],
            ['id' => 129, 'shortcode' => 'LI', 'title' => 'Liechtenstein'],
            ['id' => 130, 'shortcode' => 'LT', 'title' => 'Lithuania'],
            ['id' => 131, 'shortcode' => 'LU', 'title' => 'Luxembourg'],
            ['id' => 132, 'shortcode' => 'MO', 'title' => 'Macau SAR China'],
            ['id' => 133, 'shortcode' => 'MK', 'title' => 'Macedonia'],
            ['id' => 134, 'shortcode' => 'MG', 'title' => 'Madagascar'],
            ['id' => 135, 'shortcode' => 'MW', 'title' => 'Malawi'],
            ['id' => 136, 'shortcode' => 'MY', 'title' => 'Malaysia'],
            ['id' => 137, 'shortcode' => 'MV', 'title' => 'Maldives'],
            ['id' => 138, 'shortcode' => 'ML', 'title' => 'Mali'],
            ['id' => 139, 'shortcode' => 'MT', 'title' => 'Malta'],
            ['id' => 140, 'shortcode' => 'MH', 'title' => 'Marshall Islands'],
            ['id' => 141, 'shortcode' => 'MQ', 'title' => 'Martinique'],
            ['id' => 142, 'shortcode' => 'MR', 'title' => 'Mauritania'],
            ['id' => 143, 'shortcode' => 'MU', 'title' => 'Mauritius'],
            ['id' => 144, 'shortcode' => 'YT', 'title' => 'Mayotte'],
            ['id' => 145, 'shortcode' => 'FX', 'title' => 'Metropolitan France'],
            ['id' => 146, 'shortcode' => 'MX', 'title' => 'Mexico'],
            ['id' => 147, 'shortcode' => 'FM', 'title' => 'Micronesia'],
            ['id' => 148, 'shortcode' => 'MI', 'title' => 'Midway Islands'],
            ['id' => 149, 'shortcode' => 'MD', 'title' => 'Moldova'],
            ['id' => 150, 'shortcode' => 'MC', 'title' => 'Monaco'],
            ['id' => 151, 'shortcode' => 'MN', 'title' => 'Mongolia'],
            ['id' => 152, 'shortcode' => 'ME', 'title' => 'Montenegro'],
            ['id' => 153, 'shortcode' => 'MS', 'title' => 'Montserrat'],
            ['id' => 154, 'shortcode' => 'MA', 'title' => 'Morocco'],
            ['id' => 155, 'shortcode' => 'MZ', 'title' => 'Mozambique'],
            ['id' => 156, 'shortcode' => 'MM', 'title' => 'Myanmar [Burma]'],
            ['id' => 157, 'shortcode' => 'NA', 'title' => 'Namibia'],
            ['id' => 158, 'shortcode' => 'NR', 'title' => 'Nauru'],
            ['id' => 159, 'shortcode' => 'NP', 'title' => 'Nepal'],
            ['id' => 160, 'shortcode' => 'NL', 'title' => 'Netherlands'],
            ['id' => 161, 'shortcode' => 'AN', 'title' => 'Netherlands Antilles'],
            ['id' => 162, 'shortcode' => 'NT', 'title' => 'Neutral Zone'],
            ['id' => 163, 'shortcode' => 'NC', 'title' => 'New Caledonia'],
            ['id' => 164, 'shortcode' => 'NZ', 'title' => 'New Zealand'],
            ['id' => 165, 'shortcode' => 'NI', 'title' => 'Nicaragua'],
            ['id' => 166, 'shortcode' => 'NE', 'title' => 'Niger'],
            ['id' => 167, 'shortcode' => 'NG', 'title' => 'Nigeria'],
            ['id' => 168, 'shortcode' => 'NU', 'title' => 'Niue'],
            ['id' => 169, 'shortcode' => 'NF', 'title' => 'Norfolk Island'],
            ['id' => 170, 'shortcode' => 'KP', 'title' => 'North Korea'],
            ['id' => 171, 'shortcode' => 'VD', 'title' => 'North Vietnam'],
            ['id' => 172, 'shortcode' => 'MP', 'title' => 'Northern Mariana Islands'],
            ['id' => 173, 'shortcode' => 'NO', 'title' => 'Norway'],
            ['id' => 174, 'shortcode' => 'OM', 'title' => 'Oman'],
            ['id' => 175, 'shortcode' => 'PC', 'title' => 'Pacific Islands Trust Territory'],
            ['id' => 176, 'shortcode' => 'PK', 'title' => 'Pakistan'],
            ['id' => 177, 'shortcode' => 'PW', 'title' => 'Palau'],
            ['id' => 178, 'shortcode' => 'PS', 'title' => 'Palestinian Territories'],
            ['id' => 179, 'shortcode' => 'PA', 'title' => 'Panama'],
            ['id' => 180, 'shortcode' => 'PZ', 'title' => 'Panama Canal Zone'],
            ['id' => 181, 'shortcode' => 'PG', 'title' => 'Papua New Guinea'],
            ['id' => 182, 'shortcode' => 'PY', 'title' => 'Paraguay'],
            ['id' => 183, 'shortcode' => 'YD', 'title' => 'People\'s Democratic Republic of Yemen'],
            ['id' => 184, 'shortcode' => 'PE', 'title' => 'Peru'],
            ['id' => 185, 'shortcode' => 'PH', 'title' => 'Philippines'],
            ['id' => 186, 'shortcode' => 'PN', 'title' => 'Pitcairn Islands'],
            ['id' => 187, 'shortcode' => 'PL', 'title' => 'Poland'],
            ['id' => 188, 'shortcode' => 'PT', 'title' => 'Portugal'],
            ['id' => 189, 'shortcode' => 'PR', 'title' => 'Puerto Rico'],
            ['id' => 190, 'shortcode' => 'QA', 'title' => 'Qatar'],
            ['id' => 191, 'shortcode' => 'RO', 'title' => 'Romania'],
            ['id' => 192, 'shortcode' => 'RU', 'title' => 'Russia'],
            ['id' => 193, 'shortcode' => 'RW', 'title' => 'Rwanda'],
            ['id' => 194, 'shortcode' => 'RE', 'title' => 'Réunion'],
            ['id' => 195, 'shortcode' => 'BL', 'title' => 'Saint Barthélemy'],
            ['id' => 196, 'shortcode' => 'SH', 'title' => 'Saint Helena'],
            ['id' => 197, 'shortcode' => 'KN', 'title' => 'Saint Kitts and Nevis'],
            ['id' => 198, 'shortcode' => 'LC', 'title' => 'Saint Lucia'],
            ['id' => 199, 'shortcode' => 'MF', 'title' => 'Saint Martin'],
            ['id' => 200, 'shortcode' => 'PM', 'title' => 'Saint Pierre and Miquelon'],
            ['id' => 201, 'shortcode' => 'VC', 'title' => 'Saint Vincent and the Grenadines'],
            ['id' => 202, 'shortcode' => 'WS', 'title' => 'Samoa'],
            ['id' => 203, 'shortcode' => 'SM', 'title' => 'San Marino'],
            ['id' => 204, 'shortcode' => 'SA', 'title' => 'Saudi Arabia'],
            ['id' => 205, 'shortcode' => 'SN', 'title' => 'Senegal'],
            ['id' => 206, 'shortcode' => 'RS', 'title' => 'Serbia'],
            ['id' => 207, 'shortcode' => 'CS', 'title' => 'Serbia and Montenegro'],
            ['id' => 208, 'shortcode' => 'SC', 'title' => 'Seychelles'],
            ['id' => 209, 'shortcode' => 'SL', 'title' => 'Sierra Leone'],
            ['id' => 210, 'shortcode' => 'SG', 'title' => 'Singapore'],
            ['id' => 211, 'shortcode' => 'SK', 'title' => 'Slovakia'],
            ['id' => 212, 'shortcode' => 'SI', 'title' => 'Slovenia'],
            ['id' => 213, 'shortcode' => 'SB', 'title' => 'Solomon Islands'],
            ['id' => 214, 'shortcode' => 'SO', 'title' => 'Somalia'],
            ['id' => 215, 'shortcode' => 'ZA', 'title' => 'South Africa'],
            ['id' => 216, 'shortcode' => 'GS', 'title' => 'South Georgia and the South Sandwich Islands'],
            ['id' => 217, 'shortcode' => 'KR', 'title' => 'South Korea'],
            ['id' => 218, 'shortcode' => 'ES', 'title' => 'Spain'],
            ['id' => 219, 'shortcode' => 'LK', 'title' => 'Sri Lanka'],
            ['id' => 220, 'shortcode' => 'SD', 'title' => 'Sudan'],
            ['id' => 221, 'shortcode' => 'SR', 'title' => 'Suriname'],
            ['id' => 222, 'shortcode' => 'SJ', 'title' => 'Svalbard and Jan Mayen'],
            ['id' => 223, 'shortcode' => 'SZ', 'title' => 'Swaziland'],
            ['id' => 224, 'shortcode' => 'SE', 'title' => 'Sweden'],
            ['id' => 225, 'shortcode' => 'CH', 'title' => 'Switzerland'],
            ['id' => 226, 'shortcode' => 'SY', 'title' => 'Syria'],
            ['id' => 227, 'shortcode' => 'ST', 'title' => 'São Tomé and Príncipe'],
            ['id' => 228, 'shortcode' => 'TW', 'title' => 'Taiwan'],
            ['id' => 229, 'shortcode' => 'TJ', 'title' => 'Tajikistan'],
            ['id' => 230, 'shortcode' => 'TZ', 'title' => 'Tanzania'],
            ['id' => 231, 'shortcode' => 'TH', 'title' => 'Thailand'],
            ['id' => 232, 'shortcode' => 'TL', 'title' => 'Timor-Leste'],
            ['id' => 233, 'shortcode' => 'TG', 'title' => 'Togo'],
            ['id' => 234, 'shortcode' => 'TK', 'title' => 'Tokelau'],
            ['id' => 235, 'shortcode' => 'TO', 'title' => 'Tonga'],
            ['id' => 236, 'shortcode' => 'TT', 'title' => 'Trinidad and Tobago'],
            ['id' => 237, 'shortcode' => 'TN', 'title' => 'Tunisia'],
            ['id' => 238, 'shortcode' => 'TR', 'title' => 'Turkey'],
            ['id' => 239, 'shortcode' => 'TM', 'title' => 'Turkmenistan'],
            ['id' => 240, 'shortcode' => 'TC', 'title' => 'Turks and Caicos Islands'],
            ['id' => 241, 'shortcode' => 'TV', 'title' => 'Tuvalu'],
            ['id' => 242, 'shortcode' => 'UM', 'title' => 'U.S. Minor Outlying Islands'],
            ['id' => 243, 'shortcode' => 'PU', 'title' => 'U.S. Miscellaneous Pacific Islands'],
            ['id' => 244, 'shortcode' => 'VI', 'title' => 'U.S. Virgin Islands'],
            ['id' => 245, 'shortcode' => 'UG', 'title' => 'Uganda'],
            ['id' => 246, 'shortcode' => 'UA', 'title' => 'Ukraine'],
            ['id' => 247, 'shortcode' => 'SU', 'title' => 'Union of Soviet Socialist Republics'],
            ['id' => 248, 'shortcode' => 'AE', 'title' => 'United Arab Emirates'],
            ['id' => 249, 'shortcode' => 'GB', 'title' => 'United Kingdom'],
            ['id' => 250, 'shortcode' => 'US', 'title' => 'United States'],
            ['id' => 251, 'shortcode' => 'ZZ', 'title' => 'Unknown or Invalid Region'],
            ['id' => 252, 'shortcode' => 'UY', 'title' => 'Uruguay'],
            ['id' => 253, 'shortcode' => 'UZ', 'title' => 'Uzbekistan'],
            ['id' => 254, 'shortcode' => 'VU', 'title' => 'Vanuatu'],
            ['id' => 255, 'shortcode' => 'VA', 'title' => 'Vatican City'],
            ['id' => 256, 'shortcode' => 'VE', 'title' => 'Venezuela'],
            ['id' => 257, 'shortcode' => 'VN', 'title' => 'Vietnam'],
            ['id' => 258, 'shortcode' => 'WK', 'title' => 'Wake Island'],
            ['id' => 259, 'shortcode' => 'WF', 'title' => 'Wallis and Futuna'],
            ['id' => 260, 'shortcode' => 'EH', 'title' => 'Western Sahara'],
            ['id' => 261, 'shortcode' => 'YE', 'title' => 'Yemen'],
            ['id' => 262, 'shortcode' => 'ZM', 'title' => 'Zambia'],
            ['id' => 263, 'shortcode' => 'ZW', 'title' => 'Zimbabwe'],
            ['id' => 264, 'shortcode' => 'AX', 'title' => 'Åland Islands'],

        ];

        foreach ($items as $item) {
            \App\Models\Country::create($item);
        }*/
    }
}
